dubbo:
  application:
    id: provider
  scan:
    base-packages: com.dp.pyss.spring.cloud.alibaba.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  consumer:
    check: false
  cloud:
    subscribed-services: ${provider.application.name}

server:
  port: 8090
  servlet:
    context-path: /consumer

provider:
  application:
    name: provider