dubbo:
  application:
    id: provider
  scan:
    base-packages: com.dp.pyss.spring.cloud.alibaba.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  cloud:
    #无此配置时默认订阅所有服务
    subscribed-services: provider
server:
  port: 8078